module HomeHelper
  def get_wind_direction_image_path(wind_direction)
    path = ""
    case wind_direction
      when "N"
        path = "wind-n.png"
      when "NNE"
        path = "wind-nne.png"
      when "NE"
        path = "wind-ne.png"
      when "ENE"
        path = "wind-ene.png"
      when "E"
        path = "wind-e.png"
      when "ESE"
        path = "wind-ese.png"
      when "SE"
        path = "wind-se.png"
      when "SSE"
        path = "wind-sse.png"
      when "S"
        path = "wind-s.png"
      when "SSW"
        path = "wind-sso.png"
      when "SW"
        path = "wind-so.png"
      when "WSW"
        path = "wind-oso.png"
      when "W"
        path = "wind-o.png"
      when "WNW"
        path = "wind-ono.png"
      when "NW"
        path = "wind-no.png"
      when "NNW"
        path = "wind-nno.png"
    end
    path
  end
end
